---
name: cron
on:
  schedule:
    - cron: '0,15,30,45 * * * *'
jobs:
  cron:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: .mergem-cache
          key: main
          restore-keys: main
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      - run: bundle update
      - run: |
          bin/mergem --verbose --token=${{ secrets.TOKEN }} \
            --repo=yegor256/* \
            --repo=objectionary/* \
            --repo=polystat/*
