---
name: cron
on:
  schedule:
    - cron: '0,15,30,45 * * * *'
jobs:
  cron:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: cache
        continue-on-error: true
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      - run: bundle update
      - run: |
          bin/mergem --verbose --token=${{ secrets.TOKEN }} \
            --repo=jcabi/*
      - uses: actions/upload-artifact@v3
        with:
          name: cache
          path: .mergem-cache
